import type { Metadata } from 'next'
import { Poppins, Roboto } from 'next/font/google'
import '../globals.css'
import '@fortawesome/fontawesome-free/css/all.css'
import Header from '@/src/components/shared/Header'
import NavBar from '@/src/components/shared/NavBar'
import Footer from '@/src/components/shared/Footer'
import Copyright from '@/src/components/shared/Copyright'
import { I18nProviderClient } from '@/src/locales/client'
import dbConnect from '@/src/db/dbConnect'

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--poppins',
})
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--roboto',
})

export const metadata: Metadata = {
  title: 'LWS Shop',
  description: 'this is lws shop.Generated by create next app',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://lws-shop.vercel.app',
    siteName: 'LWS Shop',
    images: [
      {
        url: 'https://lws-shop.vercel.app/og-image.png',
        width: 1200,
        height: 630,
        alt: 'LWS Shop',
      },
    ],
  },
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  await dbConnect()
  return (
    <html lang={locale}>
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <I18nProviderClient locale={locale}>
          <Header />
          <NavBar />
          {children}
          <Footer />
          <Copyright />
        </I18nProviderClient>
      </body>
    </html>
  )
}
